### ISSUE TITLE
Introduction - paragraph as the first section of documentation

### ISSUE THREAD

**Issue by DenverCoder544** [oskariorg/oskari-documentation#16]
possible contents including
* a mention of the overall wip nature of the documentation
* what is oskari (from a techinical perspective)
* The basic concepts
* technologoy overview (java, javascript ...)
* development guidelines (https://oskari.org/documentation/development/guidelines)
* git process https://oskari.org/documentation/development/oskari-git-process

**Comment by rekjuh** [comment]
The introduction has been so far divided as follows:

Welcome
- WIP documentation, make a PR or issue in GitHub
- What is Oskari in technical perspective
- Technology overview

Basic Concepts

Development Guidelines

Git Process

**Comment by rekjuh** [comment]
Done in PR 27.

**Comment by ZakarFin** [comment]
I think this can be closed.
