### ISSUE TITLE
Clarify requirements for setting up Oskari development environment

### ISSUE THREAD

**Issue by ismogis** [oskariorg/oskari-documentation#30]
I'd have some suggestions to improve the clarity of the requirements on the page that guides developers through setting up the development environment (https://github.com/oskariorg/oskari-documentation/blob/develop/3%20Setup%20instructions/00040-SetupDevelopmentEnvironment.md). The instructions are quite clear, but a few adjustments would make them even easier to follow.

1. The database is missing from the list of requirements. It would be helpful to include a link to the page 00020-SetupDatabase.md.

2. {jetty.base} is listed as a requirement. This can be misinterpreted as needing to set up the environment variable called 'jetty.base'. If I understand correctly, the requirement is actually for the unzipped Jetty bundle.

3. The download link for the Jetty bundle is not working.

4. Under the section "Fetch Oskari-server...", it is mentioned that Git is only mandatory when contributing changes to Oskari. This should be mentioned earlier in the Requirements section.

**Comment by ZakarFin** [comment]
Thanks! Good points. The download takes you to the download page when this is shown on oskari.org, but it doesn't really work when viewed on GitHub and is misleading as such. Maybe we should include the domain just so it works as expected when viewed on GitHub.

This page is more about setting the development environment for building the code. That doesn't require the database, but then again we should review what would make sense to list here. Definitely the jetty.base reference is misplaced and should not be part of the requirements list.

**Comment by ismogis** [comment]
@ZakarFin I would prefer that this page also included guidance on how to run the application in a development environment. It could, of course, simply provide links to resources like setting up the database.

**Comment by ZakarFin** [comment]
When you read this as a page on the new Oskari.org site (found in oskari-documentation-site repo next to this one) everything under a folder like "3 Setup instructions" is shown as one page. We might need to rethink how we store these on GitHub if we want to make both read similarly and maybe concatenate the source to one page as well to make it work better on both. Then again I'm not sure if that would break how the navigation for the documentation is created on the new site. It would be nice if one could follow the documentation from either source, but we might need to compromise to get it working nicely on at least one of these.

**Comment by rekjuh** [comment]
Few comments on this issue:

"The database is missing from the list of requirements. It would be helpful to include a link to the page 00020-SetupDatabase.md."
* a PR on this which takes into account Sami's comment on the topic is on the works atm.

"{jetty.base} is listed as a requirement. This can be misinterpreted as needing to set up the environment variable called 'jetty.base'. If I understand correctly, the requirement is actually for the unzipped Jetty bundle."
* This has been fixed: "{jetty.base} refers to the oskari-server folder in an unzipped [Jetty bundle](https://oskari.org/download)"

"The download link for the Jetty bundle is not working."
* Refers to oskari.org/download at the moment.

"Under the section "Fetch Oskari-server...", it is mentioned that Git is only mandatory when contributing changes to Oskari. This should be mentioned earlier in the Requirements section."
* This has been added to requirements.

I suppose we can close this now.

**Comment by ZakarFin** [comment]
Sure, some things like the link to database instructions is not an issue when this is viewed on oskari.org as it shows the individual files as one page.  While looking at them through GitHub as separate pages they are more disjointed.
