### ISSUE TITLE
Updating frontend in development environment

### ISSUE THREAD

**Issue by ismogis** [oskariorg/oskari-documentation#31]
In the "Setup Oskari development environment" page (https://github.com/oskariorg/oskari-documentation/blob/develop/3%20Setup%20instructions/00040-SetupDevelopmentEnvironment.md), the instructions for updating the frontend state as follows.

"Note! The frontend source code is already available under {jetty.base}/oskari-frontend in the [Jetty bundle](https://github.com/oskariorg/oskari-documentation/blob/develop/download). To update it you can replace it with code found in https://github.com/oskariorg/oskari-frontend."

However, the Jetty bundle downloaded from https://oskari.org/documentation/backend/setup-jetty does not include a folder named '{jetty.base}/oskari-frontend'.

**Comment by ZakarFin** [comment]
Thanks! It's probably oskari-frontend -> sample-application, but we'll take a look at it :)

**Comment by ismogis** [comment]
@ZakarFin I had the same thought. Additionally, it seems that the files can't simply be replaced. I believe this section could be expanded to provide a bit more guidance how to setup the frontend.
